---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: tierapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: tierapp
  ports:
  - protocol: TCP
    port: 5050
    targetPort: 5050
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: tierapp
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
